pub mod active_set;
pub mod apportionment_queue;
pub mod auth;
pub mod blob;
pub mod bls_aggregate;
pub mod committee;
pub mod display;
pub mod encoding;
pub mod epoch_parameters;
pub mod event_blob;
pub mod events;
pub mod extended_field;
pub mod init;
pub mod messages;
pub mod metadata;
pub mod node_metadata;
pub mod pending_values;
pub mod pool_exchange_rate;
pub mod shared_blob;
pub mod staked_wal;
pub mod staking;
pub mod staking_inner;
pub mod staking_pool;
pub mod storage_accounting;
pub mod storage_node;
pub mod storage_resource;
pub mod system;
pub mod system_state_inner;
pub mod upgrade;
pub mod walrus_context;

pub type ActiveSet<'a> = active_set::Contract<'a>;
pub type ApportionmentQueue<'a> = apportionment_queue::Contract<'a>;
pub type Auth<'a> = auth::Contract<'a>;
pub type Blob<'a> = blob::Contract<'a>;
pub type BlsAggregate<'a> = bls_aggregate::Contract<'a>;
pub type Committee<'a> = committee::Contract<'a>;
pub type Display<'a> = display::Contract<'a>;
pub type Encoding<'a> = encoding::Contract<'a>;
pub type EpochParameters<'a> = epoch_parameters::Contract<'a>;
pub type EventBlob<'a> = event_blob::Contract<'a>;
pub type Events<'a> = events::Contract<'a>;
pub type ExtendedField<'a> = extended_field::Contract<'a>;
pub type Init<'a> = init::Contract<'a>;
pub type Messages<'a> = messages::Contract<'a>;
pub type Metadata<'a> = metadata::Contract<'a>;
pub type NodeMetadata<'a> = node_metadata::Contract<'a>;
pub type PendingValues<'a> = pending_values::Contract<'a>;
pub type PoolExchangeRate<'a> = pool_exchange_rate::Contract<'a>;
pub type SharedBlob<'a> = shared_blob::Contract<'a>;
pub type StakedWal<'a> = staked_wal::Contract<'a>;
pub type Staking<'a> = staking::Contract<'a>;
pub type StakingInner<'a> = staking_inner::Contract<'a>;
pub type StakingPool<'a> = staking_pool::Contract<'a>;
pub type StorageAccounting<'a> = storage_accounting::Contract<'a>;
pub type StorageNode<'a> = storage_node::Contract<'a>;
pub type StorageResource<'a> = storage_resource::Contract<'a>;
pub type System<'a> = system::Contract<'a>;
pub type SystemStateInner<'a> = system_state_inner::Contract<'a>;
pub type Upgrade<'a> = upgrade::Contract<'a>;
pub type WalrusContext<'a> = walrus_context::Contract<'a>;
