package com.suisdks.sui.grpc

import kotlin.test.Test
import kotlin.test.assertEquals

class SuiGrpcClientTest {
    @Test
    fun callPassesMetadataToTransport() {
        var captured: GrpcRequest? = null
        val transport = object : GrpcTransport {
            override fun unary(request: GrpcRequest): GrpcResponse {
                captured = request
                return when (request.method) {
                    "rpc.discover" -> GrpcResponse(result = mapOf("info" to mapOf("version" to "1.2.3")))
                    "sui_getLatestCheckpointSequenceNumber" -> GrpcResponse(result = "7")
                    "suix_getReferenceGasPrice" -> GrpcResponse(result = "1000")
                    "suix_getLatestSuiSystemState" -> GrpcResponse(result = mapOf("epoch" to "1"))
                    "suix_getCoins" -> GrpcResponse(result = mapOf("data" to listOf(mapOf("coinObjectId" to "c1"))))
                    "suix_getAllCoins" -> GrpcResponse(result = mapOf("data" to listOf(mapOf("coinObjectId" to "c2"))))
                    "suix_getBalance" -> GrpcResponse(result = mapOf("totalBalance" to "10"))
                    "suix_getAllBalances" -> GrpcResponse(result = listOf(mapOf("coinType" to "0x2::sui::SUI")))
                    "suix_getCoinMetadata" -> GrpcResponse(result = mapOf("symbol" to "SUI"))
                    "suix_getTotalSupply" -> GrpcResponse(result = mapOf("value" to "100"))
                    "suix_getOwnedObjects" -> GrpcResponse(result = mapOf("data" to listOf(mapOf("objectId" to "o1"))))
                    "suix_getDynamicFields" -> GrpcResponse(result = mapOf("data" to listOf(mapOf("name" to "f1"))))
                    "suix_getDynamicFieldObject" -> GrpcResponse(result = mapOf("data" to mapOf("objectId" to "df1")))
                    "suix_queryEvents" -> GrpcResponse(result = mapOf("data" to listOf(mapOf("id" to "e1"))))
                    "suix_queryTransactionBlocks" -> GrpcResponse(result = mapOf("data" to listOf(mapOf("digest" to "t1"))))
                    "sui_dryRunTransactionBlock" -> GrpcResponse(result = mapOf("effects" to mapOf("status" to "success")))
                    "sui_devInspectTransactionBlock" -> GrpcResponse(result = mapOf("effects" to mapOf("status" to "success")))
                    "sui_getEvents" -> GrpcResponse(result = listOf(mapOf("id" to "ev1")))
                    "sui_getTransactionBlock" -> GrpcResponse(result = mapOf("digest" to request.params.firstOrNull()))
                    "sui_multiGetObjects" -> GrpcResponse(result = listOf(mapOf("objectId" to "0xA")))
                    "sui_getTotalTransactionBlocks" -> GrpcResponse(result = "99")
                    "sui_multiGetTransactionBlocks" -> GrpcResponse(result = listOf(mapOf("digest" to "d1")))
                    "sui_getCheckpoints" -> GrpcResponse(result = mapOf("data" to listOf(mapOf("sequenceNumber" to "1"))))
                    "sui_getCheckpoint" -> GrpcResponse(result = mapOf("sequenceNumber" to request.params.firstOrNull()))
                    "sui_getChainIdentifier" -> GrpcResponse(result = "4c78adac")
                    "suix_getCommitteeInfo" -> GrpcResponse(result = mapOf("epoch" to (request.params.firstOrNull() ?: "latest")))
                    "sui_getProtocolConfig" -> GrpcResponse(result = mapOf("version" to (request.params.firstOrNull() ?: "latest")))
                    "suix_getNetworkMetrics" -> GrpcResponse(result = mapOf("currentTps" to 2))
                    "suix_getLatestAddressMetrics" -> GrpcResponse(result = mapOf("cumulativeAddresses" to "3"))
                    "suix_getEpochMetrics" -> GrpcResponse(result = mapOf("data" to emptyList<Any>(), "hasNextPage" to false))
                    "suix_getAllEpochAddressMetrics" -> GrpcResponse(result = listOf(mapOf("epoch" to "1")))
                    "suix_getEpochs" -> GrpcResponse(result = mapOf("data" to listOf(mapOf("epoch" to "1")), "hasNextPage" to false))
                    "suix_getMoveCallMetrics" -> GrpcResponse(result = mapOf("rank3Days" to emptyList<Any>()))
                    "suix_getCurrentEpoch" -> GrpcResponse(result = mapOf("epoch" to "5"))
                    "suix_resolveNameServiceAddress" -> GrpcResponse(result = mapOf("address" to "0xabc"))
                    "suix_resolveNameServiceNames" -> GrpcResponse(result = mapOf("data" to listOf("alice.sui"), "hasNextPage" to false))
                    "suix_getValidatorsApy" -> GrpcResponse(result = mapOf("apys" to listOf(mapOf("apy" to "0.1"))))
                    "suix_getStakes" -> GrpcResponse(result = listOf(mapOf("stakedSuiId" to "0xstake")))
                    "suix_getStakesByIds" -> GrpcResponse(result = listOf(mapOf("stakedSuiId" to "0xstake")))
                    "sui_tryGetPastObject" -> GrpcResponse(result = mapOf("status" to "VersionFound"))
                    "sui_tryMultiGetPastObjects" -> GrpcResponse(result = listOf(mapOf("status" to "VersionFound")))
                    "sui_getNormalizedMoveModulesByPackage" -> GrpcResponse(result = mapOf("m" to mapOf("name" to "m")))
                    "sui_getNormalizedMoveModule" -> GrpcResponse(result = mapOf("name" to request.params.getOrNull(1)))
                    "sui_getNormalizedMoveFunction" -> GrpcResponse(result = mapOf("name" to request.params.getOrNull(2)))
                    "sui_getMoveFunctionArgTypes" -> GrpcResponse(result = listOf("Pure"))
                    "sui_getNormalizedMoveStruct" -> GrpcResponse(result = mapOf("name" to request.params.getOrNull(2)))
                    "sui_verifyZkLoginSignature" -> GrpcResponse(result = mapOf("success" to true))
                    "sui_executeTransactionBlock" -> GrpcResponse(result = mapOf("digest" to "0xTX"))
                    "sui_getObject" -> GrpcResponse(result = mapOf("objectId" to request.params.firstOrNull()))
                    else -> GrpcResponse(result = mapOf("ok" to true))
                }
            }
        }

        val client = SuiGrpcClient(transport)
        val out = client.call(
            method = "sui_getObject",
            params = listOf("0x1", emptyMap<String, Any?>()),
            metadata = mapOf("x-api-key" to "k", "authorization" to "Bearer t"),
        )

        assertEquals("sui_getObject", captured!!.method)
        assertEquals("k", captured!!.metadata["x-api-key"])
        assertEquals("Bearer t", captured!!.metadata["authorization"])
        assertEquals("0x1", (out as Map<*, *>)["objectId"])
        assertEquals("1.2.3", ((client.discoverRpcApi() as Map<*, *>)["info"] as Map<*, *>)["version"])
        assertEquals("0x3", (client.unary(GrpcRequest("sui_getObject", listOf("0x3", emptyMap<String, Any?>()))).result as Map<*, *>)["objectId"])
        assertEquals("7", client.getLatestCheckpointSequenceNumber())
        assertEquals("1000", client.getReferenceGasPrice())
        assertEquals("1", (client.getLatestSuiSystemState() as Map<*, *>)["epoch"])
        assertEquals("c1", (((client.getCoins("0x1") as Map<*, *>)["data"] as List<*>).first() as Map<*, *>)["coinObjectId"])
        assertEquals("c2", (((client.getAllCoins("0x1") as Map<*, *>)["data"] as List<*>).first() as Map<*, *>)["coinObjectId"])
        assertEquals("10", (client.getBalance("0x1") as Map<*, *>)["totalBalance"])
        assertEquals("SUI", (client.getCoinMetadata("0x2::sui::SUI") as Map<*, *>)["symbol"])
        assertEquals("100", (client.getTotalSupply("0x2::sui::SUI") as Map<*, *>)["value"])
        assertEquals("o1", (((client.getOwnedObjects("0x1") as Map<*, *>)["data"] as List<*>).first() as Map<*, *>)["objectId"])
        assertEquals("f1", (((client.getDynamicFields("0xP") as Map<*, *>)["data"] as List<*>).first() as Map<*, *>)["name"])
        assertEquals("df1", (((client.getDynamicFieldObject("0xP", mapOf("type" to "u8", "value" to 1)) as Map<*, *>)["data"] as Map<*, *>)["objectId"])
        assertEquals("e1", (((client.queryEvents(emptyMap<String, Any?>()) as Map<*, *>)["data"] as List<*>).first() as Map<*, *>)["id"])
        assertEquals("t1", (((client.queryTransactionBlocks(emptyMap<String, Any?>()) as Map<*, *>)["data"] as List<*>).first() as Map<*, *>)["digest"])
        assertEquals("success", (((client.dryRunTransactionBlock("AQ==") as Map<*, *>)["effects"] as Map<*, *>)["status"]))
        assertEquals("success", (((client.devInspectTransactionBlock("0x1", "AQ==") as Map<*, *>)["effects"] as Map<*, *>)["status"]))
        assertEquals("ev1", ((client.getEventsByTransaction("0xT") as List<*>).first().let { (it as Map<*, *>)["id"] }))
        assertEquals("0xT", (client.getTransactionBlock("0xT") as Map<*, *>)["digest"])
        assertEquals("0xA", ((client.multiGetObjects(listOf("0xA")) as List<*>).first() as Map<*, *>)["objectId"])
        assertEquals("99", client.getTotalTransactionBlocks())
        assertEquals("d1", ((client.multiGetTransactionBlocks(listOf("0x1")) as List<*>).first() as Map<*, *>)["digest"])
        assertEquals("1", (((client.getCheckpoints() as Map<*, *>)["data"] as List<*>).first() as Map<*, *>)["sequenceNumber"])
        assertEquals("5", (client.getCheckpoint("5") as Map<*, *>)["sequenceNumber"])
        assertEquals("4c78adac", client.getChainIdentifier())
        assertEquals("9", (client.getCommitteeInfo("9") as Map<*, *>)["epoch"])
        assertEquals("latest", (client.getProtocolConfig() as Map<*, *>)["version"])
        assertEquals(2, (client.getNetworkMetrics() as Map<*, *>)["currentTps"])
        assertEquals("3", (client.getAddressMetrics() as Map<*, *>)["cumulativeAddresses"])
        assertEquals(false, (client.getEpochMetrics() as Map<*, *>)["hasNextPage"])
        assertEquals("1", ((client.getAllEpochAddressMetrics() as List<*>).first() as Map<*, *>)["epoch"])
        assertEquals(false, (client.getEpochs() as Map<*, *>)["hasNextPage"])
        assertEquals("5", (client.getCurrentEpoch() as Map<*, *>)["epoch"])
        assertEquals("0xabc", (client.resolveNameServiceAddress("alice.sui") as Map<*, *>)["address"])
        assertEquals("alice.sui", ((client.resolveNameServiceNames("0xabc") as Map<*, *>)["data"] as List<*>).first())
        assertEquals("0.1", ((((client.getValidatorsApy() as Map<*, *>)["apys"] as List<*>).first() as Map<*, *>)["apy"]))
        assertEquals("0xstake", ((client.getStakes("0xabc") as List<*>).first().let { (it as Map<*, *>)["stakedSuiId"] }))
        assertEquals("0xstake", ((client.getStakesByIds(listOf("0xstake")) as List<*>).first().let { (it as Map<*, *>)["stakedSuiId"] }))
        assertEquals("VersionFound", (client.tryGetPastObject("0x1", 1) as Map<*, *>)["status"])
        assertEquals("VersionFound", ((client.tryMultiGetPastObjects(listOf(mapOf("objectId" to "0x1", "version" to 1))) as List<*>).first().let { (it as Map<*, *>)["status"] }))
        assertEquals("m", (((client.getNormalizedMoveModulesByPackage("0x2") as Map<*, *>)["m"] as Map<*, *>)["name"]))
        assertEquals("module", (client.getNormalizedMoveModule("0x2", "module") as Map<*, *>)["name"])
        assertEquals("f", (client.getNormalizedMoveFunction("0x2", "module", "f") as Map<*, *>)["name"])
        assertEquals("Pure", (client.getMoveFunctionArgTypes("0x2", "module", "f") as List<*>).first())
        assertEquals("S", (client.getNormalizedMoveStruct("0x2", "module", "S") as Map<*, *>)["name"])
        assertEquals(true, (client.verifyZkLoginSignature("b", "s", 3, "0x1") as Map<*, *>)["success"])
        assertEquals("0xTX", (client.executeTransactionBlock("AQ==", "sig") as Map<*, *>)["digest"])
        assertEquals("0xTX", (client.executeTransactionBlock(byteArrayOf(1, 2, 3), listOf("sig")) as Map<*, *>)["digest"])
        val coreClient: GrpcCoreClient = client
        assertEquals("0xTX", (coreClient.executeTransactionBlock("AQ==", listOf("sig")) as Map<*, *>)["digest"])
        val objects = client.getObjects(listOf("0x1", "0x2"))
        assertEquals("0x1", (objects[0].result as Map<*, *>)["objectId"])
        assertEquals("0x2", (objects[1].result as Map<*, *>)["objectId"])
    }
}
